# Generated by Django 3.1.7 on 2021-02-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210224_1040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Hero_Banners',
        ),
    ]
