# Generated by Django 3.1.7 on 2021-02-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210224_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero_Banners',
            new_name='HeroBanners',
        ),
    ]
