# Generated by Django 3.1.7 on 2021-02-24 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210224_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeroBanners',
            new_name='Hero',
        ),
    ]
