# Generated by Django 3.1.7 on 2021-02-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210224_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Hero Slide'},
        ),
        migrations.RemoveField(
            model_name='hero',
            name='content',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='hero',
            name='button_text',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='hero',
            name='slide',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
