# Generated by Django 3.1.7 on 2021-02-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210224_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='', upload_to='images/')),
                ('logo_text', models.ImageField(default='', upload_to='images/')),
                ('link_1', models.CharField(default='eat', max_length=50)),
                ('link_2', models.CharField(default='drink', max_length=50)),
                ('link_3', models.CharField(default='events', max_length=50)),
                ('link_4', models.CharField(default='experience', max_length=50)),
                ('button_text', models.CharField(default='DEALS', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Navigation bar',
            },
        ),
        migrations.AlterModelOptions(
            name='herotitle',
            options={'verbose_name_plural': 'Hero Title'},
        ),
    ]
