# Generated by Django 3.1.7 on 2021-02-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210226_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='link_5',
            field=models.CharField(default='about', max_length=50),
        ),
        migrations.AddField(
            model_name='navbar',
            name='link_6',
            field=models.CharField(default='contact', max_length=50),
        ),
    ]
