# Generated by Django 3.1.7 on 2021-02-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210227_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('category_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='hero',
            name='button_text',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hero',
            name='slide',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='link_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='link_2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='link_3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='link_4',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='link_5',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='link_6',
            field=models.CharField(max_length=50),
        ),
    ]
