# Generated by Django 3.1.7 on 2021-02-28 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210227_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Top_5', models.CharField(default='Portuguese', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('Top_5_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.top5')),
            ],
        ),
    ]
