# Generated by Django 3.1.7 on 2021-02-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_top_top5'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='top',
            options={'verbose_name_plural': 'Dishes'},
        ),
        migrations.AddField(
            model_name='top',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
