# Generated by Django 3.1.7 on 2021-02-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210228_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top',
            name='description',
        ),
    ]
