# Generated by Django 3.1.7 on 2021-02-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_top_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top',
        ),
        migrations.DeleteModel(
            name='Top5',
        ),
    ]
