# Generated by Django 3.1.7 on 2021-03-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
