# Generated by Django 3.1.7 on 2021-03-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_top5_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top5',
            name='Description',
            field=models.TextField(default='Portuguese', max_length=1000),
        ),
    ]
