# Generated by Django 3.1.7 on 2021-03-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210318_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top5',
            name='Description',
            field=models.TextField(default='Portuguese'),
        ),
    ]
