# Generated by Django 3.1.7 on 2021-03-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210318_2046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Top',
            new_name='Post',
        ),
    ]
