# Generated by Django 3.1.7 on 2021-03-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210319_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='restaurant_name',
            new_name='name',
        ),
    ]
