# Generated by Django 3.1.7 on 2021-03-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20210330_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='category',
            field=models.CharField(blank=True, choices=[('featured chef', 'Featured chef'), ('featured F&B', 'Featured F&B'), ('featured ***', 'Featured ***')], max_length=100),
        ),
    ]
