# Generated by Django 3.1.7 on 2021-04-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_feature_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Appear_on',
        ),
    ]
