# Generated by Django 3.1.7 on 2021-04-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_post_eat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Eat',
            new_name='eat',
        ),
    ]
